architecture: replication

auth:
  existingSecret: secret-redis

master:
  persistence: 
    enabled: true

replica:
  persistence: 
    enabled: true

sentinel:
  enabled: true
  downAfterMilliseconds: 600
