server:
  url: ":80"
  readTimeout: 5s
  writeTimeout: 5s
  shutdownTimeout: 5s

postgres:
  username: "admin"
  host: "postgres"
  port: 5432
  dbname: "postgres"
  sslmode: "disable"

redis:
  user: "admin"
  host: "redis"
  port: 6379
  db: 1

mail:
    host:     "smtp.mail.ru"
    port:     587
    username: "intelligentmen@inbox.ru"
    identity: ""

jwt:
  issuer: "app"
  audience: ["clients"]

logger:
  type: "default"
  level: "info"
  add_source: true
  is_json: true
  set_default: true

swagger:
  version: "1.0"
  base_path: "/api/v1/"
  host: "localhost:80"
  schemes:
    - "http"
  title: "Template of API"
  description: "This is the API documentation for template API."

mode: "RELEASE"
