server:
  url: ":80"
  readTimeout: 5s
  writeTimeout: 5s
  shutdownTimeout: 5s

postgres:
  username: "admin"
  host: "postgresql-postgresql-ha-pgpool.postgres.svc.cluster.local"
  port: 5432
  dbname: "postgres"
  sslmode: "disable"

redis:
  user: "admin"
  host: "redis.redis.svc.cluster.local"
  port: 6379
  db: 1

mail:
  host: ""
  port: 0
  username: ""
  identity: ""

jwt:
  issuer: "app"
  audience: ["clients"]

logger:
  type: "default"
  level: "info"
  add_source: true
  is_json: true
  set_default: true

mode: "RELEASE"
