redis:
  user: "admin"
  host: "localhost"
  port: 6379
  db: 0

postgres:
  username: "admin"
  host: "localhost"
  port: 5432
  dbname: "postgres"
  sslmode: "disable"

server:
  host: "localhost"
  port: 8080
