apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      container: pg

  template:
    metadata:
      labels:
        container: pg
        
  spec:
    containers:
      - name: postgres-container
        image: postgres:15-alpine
        resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        ports:
          - containerPort: 80

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: postgres-hpa

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: postgres-deployment

  minReplicas: 1
  maxReplicas: 3

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50

---