controller:
  v1:
    swagger:
      version:     "1.0"
      base_path:   "/api/v1/"
      host:        "localhost:8080"
      schemes:     [ "http" ]
      title:       "Template of API"
      description: "This is the API documentation for API template."